[package]
name = "PiCa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw-window-handle = "0.4"
wgpu = "0.12"

[dependencies.windows]
version = "0.30.0"
features = [
     "Win32_Foundation",
     "Win32_Graphics_Gdi",
     "Win32_System_LibraryLoader",
     "Win32_UI_Input",
     "Win32_UI_WindowsAndMessaging",
     "Win32_System_Threading",
     "Win32_System_Performance",
     "Win32_Devices_HumanInterfaceDevice",
     "Win32_Globalization",
     "Win32_UI_Input_KeyboardAndMouse",
]
